import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Providers from "@/lib/Providers/Providers";

const fontSans = FontSans({
  subsets: ["vietnamese"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Simply Good Food",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased relative",
            fontSans.variable
          )}
        >
          {children}
        </body>
      </html>
    </Providers>
  );
}
